name: real-estate-price-prediction
channels:
  - defaults  # Adăugat canalul defaults
  - conda-forge  # Canale suplimentare (dacă ai nevoie)
dependencies:
  - python=3.10
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pandas=2.2.2
  - pymysql=1.1.0
  - pytest
  - python-dotenv
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - seaborn=0.13.2
  - sqlalchemy=2.0.40
  - pip
  - pip:
      - black
      - pylint
