name: real-estate-price-prediction
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib=3.10.1
  - numpy=2.2.4
  - pandas=2.2.3
  - pymysql=1.1.0
  - pytest 
  - python-dotenv
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - sqlalchemy=2.0.40
  - pip
  - pip:
      - black
      - pylint
