
name: Run Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        auto-activate-base: true  # activare automată
    - name: Check active environment
      run: conda info

    - name: Verifică instalarea pytest
      run: conda list | grep pytest


    - name: Run tests with pytest
      run: |
        export PYTHONPATH=.
        pytest
